version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: 
      - /code/start_server.sh
    volumes:
      - .:/code
    expose:
      - "8000"