# Generated by Django 2.0.1 on 2018-06-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('fullname', models.CharField(max_length=256)),
                ('profession', models.CharField(max_length=256)),
                ('resume_pdf', models.FileField(null=True, upload_to='resume')),
                ('project_page', models.TextField(blank=True)),
                ('resume_page', models.TextField(blank=True)),
                ('about_page', models.TextField(blank=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalPages.Email')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('typename_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.TypeName')),
            ],
            bases=('personalPages.typename',),
        ),
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.Link')),
            ],
            bases=('personalPages.link',),
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('typename_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.TypeName')),
            ],
            bases=('personalPages.typename',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('typename_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.TypeName')),
            ],
            bases=('personalPages.typename',),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(blank=True, to='personalPages.Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, to='personalPages.Language'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='personalPages.Technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='types',
            field=models.ManyToManyField(blank=True, to='personalPages.ProjectType'),
        ),
        migrations.AddField(
            model_name='person',
            name='footer_links',
            field=models.ManyToManyField(blank=True, to='personalPages.PersonLink'),
        ),
    ]
