# Generated by Django 2.0.1 on 2018-06-26 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0002_auto_20180626_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('typename_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.TypeName')),
            ],
            bases=('personalPages.typename',),
        ),
        migrations.AddField(
            model_name='project',
            name='types',
            field=models.ManyToManyField(blank=True, to='personalPages.ProjectType'),
        ),
    ]
