# Generated by Django 2.0.1 on 2018-06-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0002_auto_20180625_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256)),
                ('profession', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('project_page', models.TextField(blank=True)),
                ('resume_page', models.TextField(blank=True)),
                ('about_page', models.TextField(blank=True)),
                ('footer_links', models.ManyToManyField(blank=True, to='personalPages.Link')),
            ],
        ),
    ]
