# Generated by Django 2.0.1 on 2018-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0002_auto_20180625_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(),
        ),
    ]
