# Generated by Django 2.0.1 on 2018-06-25 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.Link')),
            ],
            bases=('personalPages.link',),
        ),
    ]
