# Generated by Django 2.0.1 on 2018-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0003_auto_20180625_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='def-name', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typename',
            name='type_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
