# Generated by Django 2.0.1 on 2018-06-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0003_auto_20180626_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
