# Generated by Django 2.0.1 on 2018-06-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0004_auto_20180625_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('typename_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.TypeName')),
            ],
            bases=('personalPages.typename',),
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('typename_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.TypeName')),
            ],
            bases=('personalPages.typename',),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='personalPages.Technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='personalPages.Language'),
        ),
    ]
