# Generated by Django 2.0.1 on 2018-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0004_link_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='resume_pdf',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
