# Generated by Django 2.0.1 on 2018-06-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0004_personlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='footer_links',
            field=models.ManyToManyField(blank=True, to='personalPages.PersonLink'),
        ),
    ]
