# Generated by Django 2.0.1 on 2018-06-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalPages', '0005_auto_20180626_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personalPages.Link')),
            ],
            bases=('personalPages.link',),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalPages.Email'),
        ),
    ]
